Practice 10
mseheda/Healthcare-Management-System pull request #9
Opened 2024-11-15 15:25 UTC by mseheda

## Feature 1: Doctor Availability and Appointment Management
This feature introduces endpoints for managing doctor availability, scheduling appointments, and retrieving available doctors for specific dates. The `/Doctor/AvailableDoctors` endpoint allows users to retrieve a list of doctors in a specific specialization, filtered by date. The `/DoctorAppointment/Schedule` endpoint enables users to schedule appointments with doctors while updating their availability. 

## Feature 2: Drug Inventory Management
The drug inventory management feature adds endpoints to monitor and update drug stock levels. The `/Drug/Check` endpoint retrieves the current stock level of a specified drug, providing real-time inventory visibility. The `/Drug/Update` endpoint updates drug stock levels, with optional notifications to pharmacy staff when stock levels fall below a predefined threshold.

2024-11-18 12:54 UTC, liudmyla-zinchenko requested changes
Please take a look at the other requirements for the assignment.
1. Clean up:
    • All the logic should be in ..Service.cs classes. Move logic from entities and from controller to services. If you need to use inheritance and polymorphism - use in service.
    (using patterns Strategy or Factory)
    • Every class, struct, enum should be place in a separate .cs file.
    • Avoid illogical cases (like get class entity and get struct entity)
    • Unnecessary peace's of code, not in use or not related for subject area. All the methods must be in use.

    2. Follow code quality and code styles: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#style-guidelines

    3. Develop features in your project:
General: 
    • Have at least 3 controllers.
    • Each controller should correspond for at least 1 service.
    • All the logic related to Data Access Layer (DAL) or Http/Smtp Client should be called from service layer. It is prohibited to call it directly from Controllers.
    • To store data it is allowed to store data in-memory or use DB.

2024-11-18 12:54 UTC, liudmyla-zinchenko commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    public ActionResult AddTimeSlot(
According to the task and REST API best practices you should have at least such Controllers:
- DoctorCotroller.cs
- DoctorAppointmentController.cs
- DrugController.cs
- DrugReportingController.cs

GET /Doctor/AvailableDoctors?specialization=Cardiology&date=2024-12-01
POST /DoctorAppointment/Schedule

GET /Drug/Check?drugName=Aspirin
POST /Drug/Update

Keep in mind, the contract suggested in the assignment is mandatory. During the check I should have the ability to use Postman (or any other similar tool), put given Url, HTTP request type, parameters and body and your designed API should work.

Note: You can keep DrugInvetoryController.cs for 
GET /Drug/Check?drugName=Aspirin
POST /Drug/Update
This is acceptable deviation

2024-11-18 12:54 UTC, liudmyla-zinchenko commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    [FromQuery] TimeSpan time)
1. To schedule (add timeslot) use POST method and pass all the required information in the _body_. It is recommended to have separate model for incoming parameters, e. g. ScheduleAppointmentRequest.cs that keeps all the required incoming fields. This recommendation is especially applicable when you have 3 or more incoming params.

2024-11-18 12:54 UTC, liudmyla-zinchenko commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Services/DoctorService.cs
> +        var dateTimeFilter = time.HasValue ? date.Date + time.Value : (DateTime?)null;
to avoid unnecessary type casting, use DateTime? (nullable) instead of var.

2024-11-18 12:54 UTC, liudmyla-zinchenko commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    [FromQuery] DateTime date,
Options to work with dates and time: 
- use DateOnly and TimeOnly classes
https://learn.microsoft.com/en-us/dotnet/api/system.dateonly?view=net-9.0
https://learn.microsoft.com/en-us/dotnet/api/system.timeonly?view=net-9.0

-  use string and DateTime.ParseExact
DateTime.ParseExact(datetime, "yyyy-MM-ddTHH:mm", null);

- use set up for json options
builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
    options.JsonSerializerOptions.Converters.Add(new JsonConverter<DateTimeOffset>());
});

- implement custom dateTime converter
options.JsonSerializerOptions.Converters.Add(new CustomDateTimeConverter());

- keep in mind that default System.Json already automatically will parse some formats for you 
[options.JsonSerializerOptions.Converters.Add(new CustomDateTimeConverter());](https://learn.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support)
thus, maybe it is not necessary to try to simplify format like 2019-04-24T14:50:17.101Z

2024-11-18 12:54 UTC, liudmyla-zinchenko commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    [FromQuery] TimeSpan? time = null)
In your design does "time" param mean time to schedule appointment, like 13:00, 14:00 ...
Or it is duration of appointment, like 30 mins, 1 hour, etc?

If it is just time to schedule then your design does not take into account time slot duration.
If it is duration of appointment then your design does not take into account exact time.

Also parameter naming leads to some confusion, so it is better to rename it.

2024-11-24 15:58 UTC, BraveheartMousy approved these changes
Accepted. Please resolve open conversation and if there are open questions, write down some responses so I can quickly understand what was changed or even just your thought process

2024-11-24 19:01 UTC, mseheda commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    [FromQuery] TimeSpan time)
Resolved by using POST with a ScheduleAppointmentRequest model to encapsulate required fields.

2024-11-24 19:02 UTC, mseheda commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Services/DoctorService.cs
> +        var dateTimeFilter = time.HasValue ? date.Date + time.Value : (DateTime?)null;
Resolved by replacing var with DateTime? for nullable date and time handling.

2024-11-24 19:02 UTC, mseheda commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    [FromQuery] TimeSpan? time = null)
Resolved by separating "time" into appointmentTime for exact scheduling and durationInMinutes for time slot duration, improving clarity and parameter naming.

2024-11-24 19:03 UTC, mseheda commented on Healthcare-Hospital-Management-System/Healthcare-Hospital-Management-System/Controllers/DoctorsController.cs
> +    [FromQuery] DateTime date,
Resolved by using DateOnly and TimeOnly for handling dates and times.

2024-11-24 19:04 UTC, merged